In [34]:
from scipy import stats
age = [13, 15, 16, 16, 19, 20, 20, 21, 22, 22, 25, 25, 25, 25, 30, 33,
33, 35, 35, 35, 35, 36, 40, 45, 46, 52, 70]

# (a) Use min-max normalization to transform the values of age to the range [0:1].
# (b) Use z-score normalization to transform the values of age.
# (c) Use normalization by decimal scaling to transform the values of age such that the transformed value
# is less than 1.
min_max = [((item - age[0])/(age[len(age)-1]-age[0])) for item in age]
z_scale = stats.zscore(age)
l = len(str(age[len(age)-1]))
dec_scale = [(item/(10**l))for item in age]
print("=== min-max normalization===")
print(min_max)
print("\n===z-score normalization===\n",z_scale)
print("\n===decimal scaling===\n ",dec_scale)

=== min-max normalization===
[0.0, 0.03508771929824561, 0.05263157894736842, 0.05263157894736842, 0.10526315789473684, 0.12280701754385964, 0.12280701754385964, 0.14035087719298245, 0.15789473684210525, 0.15789473684210525, 0.21052631578947367, 0.21052631578947367, 0.21052631578947367, 0.21052631578947367, 0.2982456140350877, 0.3508771929824561, 0.3508771929824561, 0.38596491228070173, 0.38596491228070173, 0.38596491228070173, 0.38596491228070173, 0.40350877192982454, 0.47368421052631576, 0.5614035087719298, 0.5789473684210527, 0.6842105263157895, 1.0]

===z-score normalization===
 [-1.33564599e+00 -1.17816807e+00 -1.09942912e+00 -1.09942912e+00
 -8.63212252e-01 -7.84473297e-01 -7.84473297e-01 -7.05734341e-01
 -6.26995386e-01 -6.26995386e-01 -3.90778520e-01 -3.90778520e-01
 -3.90778520e-01 -3.90778520e-01  2.91625761e-03  2.39133124e-01
  2.39133124e-01  3.96611035e-01  3.96611035e-01  3.96611035e-01
  3.96611035e-01  4.75349990e-01  7.90305812e-01  1.18400059e+00
  1.26273954e+00  1.7

In [1]:
import numpy as np   
import pandas as pd
import math  
from sklearn import datasets, linear_model, metrics  

dataset = pd.read_csv('Avocado _Dataset.csv')
df = dataset['Total Volume']
a = np.sort(df)
print(a)
  
bin1 = np.zeros((50,5))
bin2 = np.zeros((50,5))
bin3 = np.zeros((50,5))

for i in range(0,250,5):
    k = int(i/5)
    mean = (a[i]+a[i+1]+a[i+2]+a[i+3]+a[i+4])/5
    for j in range(5):
        bin1[k,j] = mean
print("Bin mean :",bin1[:10][:])

for i in range(0,250,5):
    k = int(i/5)
    median = a[i+2]
    for j in range(5):
        bin2[k,j] = median
print("Bin median :",bin2[:10][:])
        
for i in range(0,250,5):
    k = int(i/5)
    for j in range(5):
        if(a[i+j]-a[i] < a[i+4]-a[i+j]):
            bin3[k,j] = a[i]
        else:
            bin3[k,j] = a[i+4]
            
print("Bin bounderies :",bin3[:10][:])


[8.45600000e+01 3.79820000e+02 3.85550000e+02 ... 5.22886979e+07
 6.10344571e+07 6.25056465e+07]
Bin mean : [[348.546 348.546 348.546 348.546 348.546]
 [526.436 526.436 526.436 526.436 526.436]
 [570.508 570.508 570.508 570.508 570.508]
 [625.4   625.4   625.4   625.4   625.4  ]
 [677.388 677.388 677.388 677.388 677.388]
 [717.338 717.338 717.338 717.338 717.338]
 [756.092 756.092 756.092 756.092 756.092]
 [779.948 779.948 779.948 779.948 779.948]
 [810.418 810.418 810.418 810.418 810.418]
 [837.376 837.376 837.376 837.376 837.376]]
Bin median : [[385.55 385.55 385.55 385.55 385.55]
 [530.96 530.96 530.96 530.96 530.96]
 [566.57 566.57 566.57 566.57 566.57]
 [627.8  627.8  627.8  627.8  627.8 ]
 [679.51 679.51 679.51 679.51 679.51]
 [712.4  712.4  712.4  712.4  712.4 ]
 [753.78 753.78 753.78 753.78 753.78]
 [775.8  775.8  775.8  775.8  775.8 ]
 [810.61 810.61 810.61 810.61 810.61]
 [841.53 841.53 841.53 841.53 841.53]]
Bin bounderies : [[ 84.56 472.82 472.82 472.82 472.82]
 [482.26 482

In [37]:
# c
# import numpy library as np 
import numpy as np 
# import pandas library as pd 
import pandas as pd 

dataset = pd.read_csv('Avocado _Dataset.csv')
  
# show the boolean dataframe             
print(" \nBoolean Dataframe : \n\n", dataset.isnull()) 
  
# Count total NaN at each column in a DataFrame 
print(" \nCount total NaN at each column in a DataFrame : \n\n",dataset.isnull().sum()) 

 
Boolean Dataframe : 

         Date  AveragePrice  Total Volume   4046   4225   4770  Total Bags  \
0      False         False         False  False  False  False       False   
1      False         False         False  False  False  False       False   
2      False         False         False  False  False  False       False   
3      False         False         False  False  False  False       False   
4      False         False         False  False  False  False       False   
...      ...           ...           ...    ...    ...    ...         ...   
18245  False         False         False  False  False  False       False   
18246  False         False         False  False  False  False       False   
18247  False         False         False  False  False  False       False   
18248  False         False         False  False  False  False       False   
18249  False         False         False  False  False  False       False   

       Small Bags  Large Bags  XLarge Bags   type 

In [9]:
import numpy as np 
import pandas as pd 

dataset = pd.read_csv('Avocado _Dataset.csv')
cut_labels = ['old','new','recent']
cut_bins = [2014,2016,2017,2018]
dataset['year'] = pd.DatetimeIndex(dataset['Date']).year
dataset['hierarchy'] = pd.cut(dataset['year'], bins=cut_bins, labels=cut_labels)

print(dataset[['Date','hierarchy']])


             Date hierarchy
0      27-12-2015       old
1      20-12-2015       old
2      13-12-2015       old
3      06-12-2015       old
4      29-11-2015       old
...           ...       ...
18245  28-01-2018    recent
18246  21-01-2018    recent
18247  14-01-2018    recent
18248  07-01-2018    recent
18249  18-03-2018    recent

[18250 rows x 2 columns]


In [10]:
dataset['AveragePrice'][:15]

0     1.33
1     1.35
2     0.93
3     1.08
4     1.29
5      NaN
6      nil
7      NaN
8      NaN
9       na
10     NaN
11     NaN
12    1.31
13    0.99
14    1.33
Name: AveragePrice, dtype: object

In [12]:
dataset['AveragePrice'] = pd.to_numeric(dataset['AveragePrice'],errors = 'coerce')
dataset['AveragePrice']=dataset["AveragePrice"].fillna( dataset.groupby('region')['AveragePrice'].transform("mean"))
print(dataset['AveragePrice'][:15])

0     1.330000
1     1.350000
2     0.930000
3     1.080000
4     1.290000
5     1.570755
6     1.570755
7     1.570755
8     1.570755
9     1.570755
10    1.570755
11    1.570755
12    1.310000
13    0.990000
14    1.330000
Name: AveragePrice, dtype: float64


In [16]:
dataset.isnull().sum()

Date            0
AveragePrice    0
Total Volume    0
4046            0
4225            0
4770            0
Total Bags      0
Small Bags      0
Large Bags      0
XLarge Bags     0
type            0
year            0
region          0
hierarchy       0
dtype: int64

In [10]:
# b
import numpy as np 
import pandas as pd 

dataset = pd.read_csv('Avocado _Dataset.csv')
print(dataset.groupby(['year','region'])['Total Volume'].sum()) #sum of total volumes sold grouped by year and region

year  region             
2015  Albany                 4.029896e+06
      Atlanta                2.323170e+07
      BaltimoreWashington    4.064558e+07
      Boise                  3.784357e+06
      Boston                 2.745499e+07
                                 ...     
2018  Syracuse               1.046988e+06
      Tampa                  6.642055e+06
      TotalUS                5.236323e+08
      West                   9.247709e+07
      WestTexNewMexico       1.181672e+07
Name: Total Volume, Length: 216, dtype: float64


In [12]:
dataset['Date'] = pd.to_datetime(dataset['Date'])# converting string Date time into Python Date time object
print(dataset['Date'])

0       2015-12-27
1       2015-12-20
2       2015-12-13
3       2015-06-12
4       2015-11-29
           ...    
18245   2018-01-28
18246   2018-01-21
18247   2018-01-14
18248   2018-07-01
18249   2018-03-18
Name: Date, Length: 18250, dtype: datetime64[ns]


In [13]:
print(dataset.groupby([dataset['Date'].dt.year,dataset['Date'].dt.month,'region'])['Total Volume'].sum())
# sum of total volume sold grouped by year , month and region

Date  Date  region             
2015  1     Albany                   322087.44
            Atlanta                 2485896.12
            BaltimoreWashington     3953149.67
            Boise                    381243.41
            Boston                  2356821.60
                                      ...     
2018  11    Syracuse                 178546.66
            Tampa                   1166896.98
            TotalUS                86598644.56
            West                   14909847.69
            WestTexNewMexico        2007673.77
Name: Total Volume, Length: 2268, dtype: float64
